theme: jekyll-theme-minimal
locale: "en-US"

title: "Aaron Giddings"
name: "Aaron Giddings"

description: >
  PhD Student  
  University of Virginia School of Data Science  
  Computer Vision • Sports Analytics • Scientific ML

url: "https://aarongiddings.github.io"
repository: "aarongiddings/aarongiddings.github.io"

logo: "/images/2025-Aaron-Giddings.png"

show_downloads: false

github_username: aarongiddings
email: your_email@virginia.edu
